################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

[en.params]
home = "Home"
# footer content
footer_content = "GPM Parks - Powering Tomorrow with Solar Innovation. Each solar plant developed by GPM Parks contributes to reducing greenhouse gas emissions, lowering dependence on imported fossil fuels, stabilizing long-term electricity costs, and supporting Morocco’s renewable-energy objectives hrough technically robust, environmentally responsible, and economically viable solar solutions."
copyright = "Copyright © GPM Parks, 2025 All rights reserved"


################################### French language #####################################
[fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2

[fr.params]
home = "Accueil"
# footer content
footer_content = "Lorem ipsum dolor amet consectetur adipisicing elit sed eiusm tempor incididunt ut labore dolore magna aliqua enim ad minim veniam quis nostrud exercitation ullamaboris nisi ut aliquip.exea commodo consequat. Duis aute irure dolor in reprehenderit. Lorem ipsum dolor amet consectetur adipisicing elit sed eiusm tempor incididunt ut labore dolore magna aliqua enim ad minim veniam quis nostrud exercitation ullamaboris nisi ut aliquip.exea commodo consequat. Duis aute irure dolor in reprehenderit."
# copyright
copyright = "Copyright © GPM Parks, 2025 All rights reserved"
