############# French navigation ##############

# main menu
#[[main]]
#name = "GPM Holding"
#url = "https://gp-maroc.gp-maroc.ma/"
#weight = 7

[[main]]
name = "About"
url = "#about"
weight = 1

[[main]]
name = "Products"
url = "#products"
weight = 2

[[main]]
name = "Manufacturing & Technology"
url = "#manufacturing"
weight = 3

[[main]]
name = "Project Solutions"
url = "#solutions"
weight = 4

[[main]]
name = "Resources"
url = "#resources"
weight = 5

[[main]]
name = "Contact"
url = "#contacts"
weight = 6

# footer menu
[[footer_menu]]
name = "GPM Holding"
url = "https://gp-maroc.gp-maroc.ma/"
weight = 1

# footer bottom links
[[footer]]
name = "Terms of Service"
url = "terms/"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 2
