############# French navigation ##############

# main menu
[[main]]
name = "GPM Holding"
url = "https://gp-maroc.gp-maroc.ma/"
weight = 8

[[main]]
name = "About"
url = "#about"
weight = 2

[[main]]
name = "Products"
url = "#products"
weight = 3
hasChildren = true

[[main]]
parent = "Products"
name = "Manufacturing & Technology"
url = "#manufacturing"
weight = 4

[[main]]
parent = "Products"
name = "Project Solutions"
url = "#solutions"
weight = 5

[[main]]
name = "Contact"
url = "#contacts"
weight = 7

# footer menu
[[footer_menu]]
name = "GPM Holding"
url = "https://gp-maroc.gp-maroc.ma/"
weight = 1

# footer bottom links
[[footer]]
name = "Terms of Service"
url = "terms/"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 2
