############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "#about"
weight = 2

#[[main]]
#name = "GPM Services"
#url = "service/"
#weight = 6

#[[main]]
#name = "GPM Mobility"
#url = "service/"
#weight = 7

#[[main]]
#name = "Blog"
#url = "blog/"
#weight = 4

#[[main]]
#name = "Team"
#url = "team/"
#weight = 6

[[main]]
weight = 3
name = "Our Entities"
hasChildren = true

  [[main]]
  parent = "Our Entities"
  name = "GPM Parks"
  url = "/"
  weight = 1

  [[main]]
  parent = "Our Entities"
  name = "Solaris"
  url = "/"
  weight = 2

  [[main]]
  parent = "Our Entities"
  name = "Polysilicon"
  url = "/"
  weight = 3

  [[main]]
  parent = "Our Entities"
  name = "GPM Services"
  url = "/"
  weight = 4

  [[main]]
  parent = "Our Entities"
  name = "GPM Mobility"
  url = "/"
  weight = 5

[[main]]
name = "Contact"
url = "#contacts"
weight = 4

# footer menu
[[footer_menu]]
name = "GPM Parks"
url = "/"
weight = 1

[[footer_menu]]
name = "Solaris"
url = "/"
weight = 2

[[footer_menu]]
name = "Polysilicon"
url = "/"
weight = 3

[[footer_menu]]
name = "GPM Services"
url = "/"
weight = 4

[[footer_menu]]
name = "GPM Mobility"
url = "/"
weight = 5

# footer bottom links
[[footer]]
name = "Terms of Service"
url = "terms/"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 2
